#!/usr/bin/env bash
# A bash script that configures a brand new Ubuntu machine to the asked requirements

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i "21i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
