#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely
# with a "sleep 2" in etween each iteration
# "I am invincible!!!" when recieving a SIGTERM signal

while ( true )
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
