#!/usr/bin/env bash
# A bash script that displays the time for 12 hours and 59 minutes
# Display hours from 0 to 12
# Display minutes from 1 to 59

i=0
k=13
hour=0
while [ $i != $k ]
do
	j=0
	echo "Hour: $hour"
	while [ $j -ne 59 ]
	do
		j=$((j+1))
		echo $j
	done
	hour=$((hour+1))
	((i++))
done
