#!/usr/bin/env bash
# A bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
facebook='8.8.8.8 facebook.com'
hosts=/etc/hosts
cp $hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "$facebook">>~/hosts.new
cp -f ~/host.new /etc/hosts
